"""Reproduce the complete TSBM submission package.

Run from the package directory:
    python run_all.py

This creates all figures, CSV/JSON tables, robustness/sensitivity outputs,
ablation analyses, and run metadata in the outputs/ directory.
"""
from __future__ import annotations

from pathlib import Path
import json
import platform
import numpy as np
import scipy

import generate_all_figures
import tsbm_rigor_analysis
import ablation_analysis


def main() -> None:
    out = Path("outputs")
    (out / "figures").mkdir(parents=True, exist_ok=True)
    (out / "tables").mkdir(parents=True, exist_ok=True)

    print("Generating manuscript figures and base tables...", flush=True)
    generate_all_figures.generate_all(out)

    print("Running base/stability/consistency checks...", flush=True)
    tsbm_rigor_analysis.write_base_outputs(out)

    print("Running local sensitivity analysis...", flush=True)
    tsbm_rigor_analysis.write_sensitivity_outputs(out)

    print("Running global robustness analysis (400 Latin-hypercube draws)...", flush=True)
    tsbm_rigor_analysis.write_robustness_outputs(out, n=400)

    print("Combining rigor outputs...", flush=True)
    tsbm_rigor_analysis.combine_rigor_outputs(out)

    print("Running structural ablation analysis...", flush=True)
    ablation_analysis.run(out)

    with open(out / "tables" / "global_robustness.json") as f:
        robustness = json.load(f)
    manifest = {
        "generated_files_note": "All manuscript figures, tables, robustness outputs, and ablation outputs are regenerated by run_all.py.",
        "python": platform.python_version(),
        "numpy": np.__version__,
        "scipy": scipy.__version__,
        "robustness_draws": robustness["n"],
        "bdnf_only_robustness_fraction": robustness["bdnf_only_fraction"],
        "multi_output_robustness_fraction": robustness["multi_output_fraction"],
    }
    with open(out / "run_manifest.json", "w") as f:
        json.dump(manifest, f, indent=2)

    print("\nComplete. Outputs written to:")
    print("  outputs/figures")
    print("  outputs/tables")


if __name__ == "__main__":
    main()
