"""Reproduce the complete TSBM analysis package.

Double-click/run this file in Thonny to open the Tkinter interface.
For command-line use, add ``--cli``.
"""
from __future__ import annotations

from pathlib import Path
import json
import platform
import numpy as np
import scipy

import generate_all_figures
import generate_corrected_figures
import tsbm_rigor_analysis
import ablation_analysis
import extended_reproducibility_analysis


def main(
    output_dir: str | Path = "outputs",
    robustness_n: int = 400,
    figure_set: str = "revised",
    include_extended: bool = True,
    extended_n: int = 400,
) -> dict:
    """Run all selected analyses and write a machine-readable run manifest."""
    if robustness_n < 2:
        raise ValueError("Robustness draws must be at least 2.")
    if include_extended and extended_n < 2:
        raise ValueError("Extended-analysis draws must be at least 2.")

    out = Path(output_dir)
    (out / "figures").mkdir(parents=True, exist_ok=True)
    (out / "tables").mkdir(parents=True, exist_ok=True)

    print("Generating manuscript figures and base tables...", flush=True)
    if figure_set == "original":
        generate_all_figures.generate_all(out)
    else:
        generate_corrected_figures.generate_all(out)

    print("Running base/stability/consistency checks...", flush=True)
    tsbm_rigor_analysis.write_base_outputs(out)

    print("Running local and multi-output sensitivity analyses...", flush=True)
    tsbm_rigor_analysis.write_sensitivity_outputs(out)

    print(f"Running global robustness analysis ({robustness_n} Latin-hypercube draws)...", flush=True)
    tsbm_rigor_analysis.write_robustness_outputs(out, n=robustness_n)

    print("Combining rigor outputs...", flush=True)
    tsbm_rigor_analysis.combine_rigor_outputs(out)

    print("Running structural ablation analysis...", flush=True)
    ablation_analysis.run(out)

    extended_manifest = None
    if include_extended:
        extended_dir = out / "extended"
        print(f"Running extended reproducibility analyses ({extended_n} draws)...", flush=True)
        extended_manifest = extended_reproducibility_analysis.run(extended_dir, n=extended_n)

    with open(out / "tables" / "global_robustness.json") as f:
        robustness = json.load(f)

    manifest = {
        "generated_files_note": (
            "Manuscript figures, tables, robustness outputs, sensitivity outputs, "
            "ablation outputs, and optional extended outputs were regenerated by run_all.py."
        ),
        "python": platform.python_version(),
        "numpy": np.__version__,
        "scipy": scipy.__version__,
        "figure_set": figure_set,
        "robustness_draws": robustness["n"],
        "bdnf_only_robustness_fraction": robustness["bdnf_only_fraction"],
        "multi_output_robustness_fraction": robustness["multi_output_fraction"],
        "extended_analysis_included": bool(include_extended),
        "extended_draws": extended_n if include_extended else 0,
        "extended_manifest": extended_manifest,
    }
    with open(out / "run_manifest.json", "w") as f:
        json.dump(manifest, f, indent=2)

    print("\nComplete. Outputs written to:")
    print(f"  {out / 'figures'}")
    print(f"  {out / 'tables'}")
    if include_extended:
        print(f"  {out / 'extended'}")
    return manifest


def get_gui_spec():
    """Return the Tkinter task definition used by this script and the master launcher."""
    from tsbm_gui import OptionSpec, TaskSpec

    def runner(output_dir: Path, options: dict) -> None:
        figure_label = str(options["figure_set"])
        figure_set = "original" if figure_label == "Original figures" else "revised"
        main(
            output_dir=output_dir,
            robustness_n=int(options["robustness_n"]),
            figure_set=figure_set,
            include_extended=bool(options["include_extended"]),
            extended_n=int(options["extended_n"]),
        )

    return TaskSpec(
        title="Run Complete TSBM Package",
        description=(
            "Runs the figure generator, stability and consistency checks, local and multi-output sensitivity, "
            "global robustness, structural ablation, and optionally the extended reproducibility analyses. "
            "All generated images appear in the gallery for saving or basic non-destructive editing."
        ),
        runner=runner,
        default_output="outputs",
        options=(
            OptionSpec(
                key="figure_set", label="Figure set", kind="choice", default="Revised larger-font figures",
                choices=("Revised larger-font figures", "Original figures"),
            ),
            OptionSpec(
                key="robustness_n", label="Robustness draws", kind="int", default=400,
                help_text="Use 20-50 for a quick test or 400 for the manuscript run.",
            ),
            OptionSpec(
                key="include_extended", label="Run extended analyses", kind="bool", default=True,
                help_text="Includes threshold uncertainty, event ordering, widened gains, and trade-offs.",
            ),
            OptionSpec(
                key="extended_n", label="Extended-analysis draws", kind="int", default=400,
                help_text="Used only when extended analyses are selected.",
            ),
        ),
        run_button_text="Run complete package",
        warning="The complete 400-draw package can take several minutes. Use smaller draw counts for a quick test.",
    )


if __name__ == "__main__":
    import argparse
    import sys

    if "--cli" in sys.argv:
        parser = argparse.ArgumentParser(description="Reproduce the complete TSBM analysis package.")
        parser.add_argument("--cli", action="store_true", help=argparse.SUPPRESS)
        parser.add_argument("--output", default="outputs")
        parser.add_argument("--robustness-n", type=int, default=400)
        parser.add_argument("--figure-set", choices=["revised", "original"], default="revised")
        parser.add_argument("--skip-extended", action="store_true")
        parser.add_argument("--extended-n", type=int, default=400)
        args = parser.parse_args()
        main(
            output_dir=args.output,
            robustness_n=args.robustness_n,
            figure_set=args.figure_set,
            include_extended=not args.skip_extended,
            extended_n=args.extended_n,
        )
    else:
        from tsbm_gui import launch_task_gui
        launch_task_gui(get_gui_spec())
